/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/aivideos/editvideos/Camera.vue')['default']
    DivSelect: typeof import('./src/components/aivideos/editvideos/DivSelect.vue')['default']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FgImg: typeof import('./src/components/aivideos/editvideos/FgImg.vue')['default']
    FooterNva: typeof import('./src/components/globals/FooterNva.vue')['default']
    Montion: typeof import('./src/components/aivideos/editvideos/Montion.vue')['default']
    NavBar: typeof import('./src/components/globals/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeSelection: typeof import('./src/components/aivideos/editvideos/SizeSelection.vue')['default']
    StartButton: typeof import('./src/components/aivideos/StartButton.vue')['default']
    Taxtarea: typeof import('./src/components/aivideos/editvideos/Taxtarea.vue')['default']
    VideoCard: typeof import('./src/components/aivideos/VideoCard.vue')['default']
  }
}
